#!/bin/sh -e

# Apply a patch to remove the perl dependency.
patch -p1 < kernel-no-perl.patch

# Copy Config to Directory
cp config .config

# Ensure config is compatible with a new version.
make olddefconfig

# Make
make

# Install Modules
make INSTALL_MOD_PATH="$1/usr" INSTALL_MOD_STRIP=1 modules_install

# `make install` doesn't create the directory.
mkdir -p "$1/boot"

# Install the Kernel
make INSTALL_PATH="$1/boot" install

# Rename the kernel to match the current version.
mv "$1/boot/vmlinuz"    "$1/boot/vmlinuz-$2"
mv "$1/boot/System.map" "$1/boot/System.map-$2"

# Setup the EFI directory structure.
mkdir -p "$1/boot/EFI/boot"

# Build the EFI binary.
objcopy \
	--add-section .osrel="/etc/os-release" --change-section-vma .osrel=0x20000 \
	--add-section .cmdline="/boot/cmdline.txt" --change-section-vma .cmdline=0x30000 \
	--add-section .linux="$1/boot/vmlinuz-$2" --change-section-vma .linux=0x40000 \
	"linuxx64.efi.stub" "$1/boot/EFI/boot/bootx64.efi"
